name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  ethereum:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: cd ./evm && make dependencies
